[package]
name = "flag"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
